name: NSE Bot

on:
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    concurrency:
      group: stockerbhai-bot
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Commit state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add state.json status.json

          git commit -m "update bot state" || echo "No changes"

          git pull --rebase origin main

          git push
